### ISSUE TITLE
Add Fundamental Arithmetic Operations and Write Tests

### ISSUE THREAD

**Issue by AbhijitSarode** [AbhijitSarode/Advanced-Math-Kit#1]
Implement four fundamental arithmetic operations, each operation can **take two or more inputs**. Write tests to cover various scenarios including edge cases

**Tasks: Implement Fundamental Operations**
- [x] Addition
- [x] Subtraction
- [x] Multiplication
- [x] Division

**Tasks: Implement Tests for Fundamental Operations**
- [x] Add Tests for Addition:
    - [x] Addition by positive numbers, negative numbers, decimals etc
    - [x] Addition by null, NaN, Infinity, undefined etc
    - [x] Warn if result is infinity
- [x] Add Tests for Subtraction:
    - [x] Subtraction by positive numbers, negative numbers, decimals etc
    - [x] Subtraction by null, NaN, Infinity, undefined etc
- [x] Add Test for Multiplication:
    - [x] Multiplication by positive numbers, negative numbers, decimals etc 
    - [x] Multiplication by null, NaN, infinity, undefined etc
    - [x] Warn if result is infinity
- [x] Add Test for Division:
    - [x] Division by positive numbers, negative numbers, decimals etc
    - [x] Division by small extremely small number to get Infinity
    - [x] Numerator is null, NaN, infinity, undefined
    - [x] Denominator is null, NaN, infinity, undefined, 0
    - [x] Warn if result is infinity
